### ISSUE TITLE
Need a "Non-Dealer" unifying term

### ISSUE THREAD

**Issue by LockerM** [DeckofAdventures/TheGame#104]
## Need a term for non-dealers that's uniform across ally/enemy NPCs

From #88 comment from @CBroz1, we need a term for non-dealers that isn't as prescriptive as "Bystander" vs. "Minion".

> > I'd prefer to have a unified term for non-dealer so that their allegiance is ambiguous
> 
> A: Are they a dealer?
> B: No, they're a X
> If X could be bystander or minion, saying which gives hints at where the narrative 'should' go.

> I also don't love the asymmetry between bystander and minion. The former sounds passive (which, if DM-NPC or allied combatant, they're not) and the latter sounds weak ('yeah, you can defo oneshot this one') when that may not be the case at higher levels

## Initial proposed fix/suggested resolution

My proposal is that "Minion" should be converted into a creature that is specifically controlled by a Dealer (Player or GM) such as the Necromancer using a Skeleton they control, versus a [INSERT NEW TERM HERE] being of its own free will and mind and indicating they act freely of a Dealer. 

We can stick with NPC as a sweeping term, though I like the flavor of Dealer being card-based if we can find a different term that still has that same feeling/flavor. 

## Post-resolution update steps 

When resolved, we would need to make updates to Player Guides and GM Guide to ensure consistency across all docs.

**Comment by CBroz1** [comment]
@LockerM - Do any of these ring true for you? 
- underling
- hireling
- lackey
- vassal
- henchman
- stooge
- sycophant
- myrmidon

**Comment by CBroz1** [comment]
@LockerM - Do any of these ring true for you? 
- underling
- hireling
- lackey
- vassal
- henchman
- stooge
- sycophant
- myrmidon

**Comment by LockerM** [comment]
I'm trying to think if there's a unifying term that keeps the card player flavor since we're looking for a term that would be equally useful when talking about a sailor on a ship or a Duke or Ambassador of a prominent nation that is not a Dealer. 

Some card player terms I saw were (bolded some of my favorites below):

- **Actor** 
- Shuffler
- Participant
- Cardshark (Shark?) 
- Cardsharp (Sharp?) 
- Sharper
- Cardholder (**Holder?**) 
- Trouper 
- **Trooper**
- Bargainer
- Bluffer
- Gambler
- Dealt

**Comment by CBroz1** [comment]
I'm fine with just saying 'NPC'. I imagine the contrast btwn low-level Dealer and high-level non-Dealer will blur over time. If we need a term, I'd pick Trooper or Underling

**Comment by LockerM** [comment]
From PR comment:

The term "NPC" feels fairly comprehensive to include all creatures (including Dealers) so I don't know that we would need to identify them in the Bestiary as NPC vs. Dealer or if we simply would indicate in the Bestiary if they're a Dealer and consider them all NPCs (or if only Player PCs are called Dealers and we revert to all GM controlled characters are now NPCs).

So far in this scope we have Dealer, Companion, Minion, and NPC. 

A Dealer can add a Power to gain control over a Companion, or use a different Power to summon a Minion. Should this be streamlined or modified in some way?

**Comment by LockerM** [comment]
Modifying the PGF in current PR to remove Bystanders and Minions. 

Now we have:
1. Dealers
2. NPCs
3. Companions

A Minion (previously conceived) is a different type of Companion, but this will help with the distinction. Technically a Minion and a Companion are both controlled by Dealers, and implying 'minion' only works on GM PCs where Companions are for PCs would get confusing. So Minions are now Companions as well.

**Comment by D-D-2** [comment]
Just for my own clarification. 
- Companion: GM/PC controlled creature that draws from their own deck(s). 
- NPCs: Creatures that do not draw from their own deck, but may make a draw from a GM General deck. 
- Dealers: Self sustaining creatures that draw from their own deck and make their own choices.

**Comment by LockerM** [comment]
**Current Version**

Companions share draws from their Dealer's deck, similar to the previous conception of Minions. 

**Potential Future State** 

Over time, or at higher levels, Companions may advance in power high enough that in my vision they would become a second Dealer that a player could control and in that case would then draw from their own deck.
