### ISSUE TITLE
Fix: Lend Aid - Card 'given'

### ISSUE THREAD

**Issue by LockerM** [DeckofAdventures/TheGame#105]
## Update Lend Aid to have user give their card to the ally

Currently, Lend Aid is a Minor Action requiring no FP and no Stamina to use. Also, when the same target is given Lend Aid often they mill their cards quickly because they are usually drawing both cards from Upper Hand.

Proposal: When you use Lend Aid, draw the top card, face down. Give that card to the target of Lend Aid. When that creature makes their next check, they draw 1 card from their deck and also the Lend Aid card to simulate Upper Hand.

**Comment by D-D-2** [comment]
Some things to consider:
 - what happens if the card is an Ace? 
 - which discard pile does the card go into? Does it depend on if the card is the one used?

**Comment by LockerM** [comment]
Good question @D-D-2 - how would the below resolution sound to you? 

- The card given by Lend Aid is a temporary gift to the target. Any Aces are reserved as Fate Cards by the Support (who uses Lend Aid), and the card once drawn is placed back in the Support's discard pile. 

This serves the purpose of accelerating the stamina drain of the Support but won't make that Support feel 'bad' if they gave an Ace away and didn't get to reserve it as a Fate Card. Since this always affects the next draw (rather than being able to reserve it) it would hopefully not be too difficult to keep track of the extra card once given to then be returned to the proper discard pile. 

In Virtual Play, the Lend Aid card would be drawn without being flipped, and then when the target of Lend Aid makes a check the Support will flip their reserved card and the target of Lend Aid can choose which card to use (the closer card since it is meant to simulate Upper Hand).

**Comment by D-D-2** [comment]
I like that additional clarity. On a VTT it might feel slightly awkward for the players/I could see some people make mistakes on this, but I don't think that should stop us from designing it this way.
