### ISSUE TITLE
Make explicit: equipping a new weapon or changing weapons is a minor action 

### ISSUE THREAD

**Issue by LockerM** [DeckofAdventures/TheGame#106]
## Clarify in Action rules in PGF

We should explicitly state that changing or equipping weapons requires a Minor Action. 

Having a table for time it takes to remove a shield, don/doff armor, would be helpful too.

**Comment by CBroz1** [comment]
I see this level of complexity as "Proposals for GM", not in player guide

**Comment by LockerM** [comment]
Agreed, we can mention Minor Actions in the GM Guide and have an expanded list for reference.

"A character who wishes to change weapons may do so as a Minor Action." 

Dropping an item should be a free action, we can include that in the GM guide as well. 

We can also add a table for time taken to don/doff and equip a shield, etc. Below is an initial proposal for that timing. 

Unequip a shield - free action to drop it.
Don Armor: 
- Light + Medium - 1 Minute
- Heavy + Gleaming - 10 Minutes

Doff Armor:
- Light - 1 Round
- Medium - 2 Rounds
- Heavy + Gleaming - 1 Minute
