### ISSUE TITLE
Is there a limit on Free Actions?

### ISSUE THREAD

**Issue by LockerM** [DeckofAdventures/TheGame#107]
## How many 'Free' Actions can be taken each turn? 

From playtesting, how many free actions can be taken each turn?

**Comment by CBroz1** [comment]
"as many as can be reasonably completed in 6 seconds"

**Comment by D-D-2** [comment]
I don't believe this is something that would make sense to hard code in the ruleset, however a sentence or two of advice to give to a GM on this topic is warranted. Each GM is going to play this differently at their table anyway, overruling a rule we make up either way.

**Comment by LockerM** [comment]
Agreed with both of you @CBroz1 and @D-D-2 - we can include in the GM guide that Free Actions should be limited only to what makes sense in the moment. If a Character were to use 10 free actions in a turn, maybe that makes sense in one context but not in another one, so I agree that 'hard coding' something wouldn't be the right approach. 

I propose we add a small note in the GM guide using @CBroz1's suggestion above and encourage the GM to decide for themselves what makes sense at their table and in any given context.

**Comment by CBroz1** [comment]
I think there are a set of rules that we don't expect anyone to follow - as house rules will take over - but we need something on paper to settle disagreements. It could be a section for "Default House Rules"

**Comment by LockerM** [comment]
See "Default House Rules" issue here - https://github.com/DeckofAdventures/TheGame/issues/119
