### ISSUE TITLE
Cones and Cubes in terms of Spaces and distance 

### ISSUE THREAD

**Issue by LockerM** [DeckofAdventures/TheGame#108]
## Cones and Cubes in Spaces and Distance

How do they work and how do we describe them, where, and how do we specify within Power descriptions?

Can we get a few 'templates' together that can visually show what a Cone looks like, how many spaces is standard, and same with Cubes.

**Comment by CBroz1** [comment]
**First Draft**
Imagined: 

![Range-Imagined](https://user-images.githubusercontent.com/9404707/184499038-4f6f13ee-b123-4a52-90bd-49fc80198026.png)

Grid: 

![Range-grid](https://user-images.githubusercontent.com/9404707/184499034-820da7f2-b7c3-48ea-97d5-6889026cfd0b.png)

Hex: 

![Range-hex](https://user-images.githubusercontent.com/9404707/184499035-8579d64b-13dc-4ba2-aefa-c9407af832d3.png)

**Comment by CBroz1** [comment]
Cone N: the radius of a cone is N squares or N-0.5 hex. The line angle is defined by the far-most corner of the spaces covered when the cone is N spaces wide.

Aura N: the radius of the aura is equal to half the caster's size plus N squares or the next intersection after N-1 hex

After measuring this shape, the caster may place it wherever they wish. Any creature in a space covered by the shape is affected.

**Comment by LockerM** [comment]
These images and the description look good to me. 

We can add these as images in the mechanics folder of TheGame and add that language into the next set of changes once we merge this GM PR

**Comment by LockerM** [comment]
To add: Lines
