### ISSUE TITLE
Clarify: Movement through friendly space but not enemy space

### ISSUE THREAD

**Issue by LockerM** [DeckofAdventures/TheGame#112]
## To Clarify in PGF: Moving through an ally's space, but not an enemy's space

Need to clarify in the PGF. When moving during combat, you can move through a friendly creature's space but cannot end your turn on that space. You cannot move through a hostile creature's space or move between two hostile creatures' spaces if they are adjacent. 

## Question

Also, are there any Actions or Powers that someone can use to 'swap' spaces with an adjacent ally? Maybe a Defender Minor Power?

**Comment by D-D-2** [comment]
To clarify the adjacent enemy rule: 

Cannot move through a space where 2 hostile creatures are on either side? I've got a diagram below. 
H=Hostile 
_ = empty 
P=Player 

     H
P--> _ 
     H
In this example, the player wouldn't be able to move through that empty space, correct? @CBroz1 @LockerM

**Comment by CBroz1** [comment]
I thought 'adjacent' was ambiguous, so I propose a clarification [here](https://github.com/DeckofAdventures/TheGame/pull/127#discussion_r956593120)

**Comment by LockerM** [comment]
*Copied from PR Comment for clarification* 

Agreed with @CBroz1 on adjusting language away from Adjacent - better to be too specific than not enough. Since we don't allow for reaction-based attacks of opportunity I think allowing enemies (and allies) to create a 'line' that can't be passed allows for some form of similar battlefield control. If there is a full space between the enemies (like in @D-D-2's example above) a creature can move through it, but if the 'H | H' are standing within 1 space of each other (meaning next to each other) then you can't move 'through' them.

In the first two examples, if there were walls on either side of the set of enemies you would need to defeat one of them in order to move past rather than being able to move 'through' the space that they control by being within 1 space of each other.

This also allows in a narrow 2-space wide hallway a Defender and Martial to stand side by side and prevent the goblins from rushing the Support who stands 3 spaces farther back down the hallway.
