### ISSUE TITLE
Add Archetype List (v1 - Maybe just 4-6 Archetypes to start) 

### ISSUE THREAD

**Issue by LockerM** [DeckofAdventures/TheGame#115]
## Adding Archetypes underneath each Role 

On Character Creation, you select a Role. At Level 3 in that Role you select an Archetype. 

Creating 3-4 Archetypes per Role is a good foundation, but for b2 it might be good to just have 1-2 Archetypes per Role so post-level 3 players can choose how to specialize their Character.

Each Archetype would have a unique Passive, and unique Minor & Major Actions, with each being a pre-req of the previous one. On level 3 you get the Passive and a Minor or Major, then at level 4 you unlock the next one on the tree, at level 5 another, etc. 

For Beta testing sticking with 5 as the soft cap we can accelerate the Archetype Power acquisition, but longer term if the leveling scale went up to 10 or more we could spread it out where you gain Archetype powers every other level or at specific levels instead.

**Comment by LockerM** [comment]
Current Archetype list in progress is being worked on here: https://docs.google.com/spreadsheets/d/1q5L7axZkAVFV9ULul5Om_pXB1aZFsuVR2-CXnBSGiZc/edit#gid=488885253

**Comment by CBroz1** [comment]
Recent discussion: an archetype is streamlined version of a role, no player choice. Someone could depart from this path at any time in a-la-carte method, sacrificing more powerful late-stage items

**Comment by LockerM** [comment]
Archetypes are pre-made characters that fall within a certain Role having chosen specific Powers on Level up. There are Power Skill Trees that require increasing investment as level increases to get to a 'capstone' ability for a specific Archetype. 

Players can choose to pursue that 'capstone' ability of an Archetype while buying other Powers a-la-carte, or as they advance they can go from using the "Assassin Level 2" character sheet to the "Assassin Level 3" character sheet.

**Comment by LockerM** [comment]
The initial proposed archetypes are:

**Support**
- Alchemist
- Shaman

**Martial**
- Assassin
- Blood Warrior

**Caster**
- Necromancer
- Elementalist

**Defender**
- Crusader
- Reckoner
