### ISSUE TITLE
Revise milestones

### ISSUE THREAD

**Issue by CBroz1** [DeckofAdventures/TheGame#116]
Currently we have explicit milestones (e.g., `1.0.0b2`) that are implicitly yolked to development stages (e.g., "closed beta").

I propose...
1. Changing to a more generic system
   - `1.0.0aX` means "this will be addressed within alpha revisions"
   - `1.0.0bX` means "this will be addressed within beta revisions"
   - `1.0.X` means "this will be addressed within `1.0` versions" - later split into `1.0.0aX`. `1.0.0bX`, `1.0.1aX`, etc
   - `1.X.0` means "this will be addressed before `2.0.0`" - these will need some periodic review, like Iced items
   - no label means "needs assignment"
2. Labeling items for the next PR(s) with either
   - The project board Sprint label for a given assignee 
   - Or explicit values of `X` (e.g., `1.0.0a5` for ~10 items)
3. For development stages
   - `1.0.0b1` is the beginning of closed beta
   - `1.0.1` is the beginning of open beta
   - Depending on the nature of the changes, the next development phase would either be `1.2.0` or `2.0.0`

@LockerM - What do you think?

**Comment by LockerM** [comment]
I agree with this proposal and think it is a clean solution that scales with our development approach and separates dev milestones from playtest milestones. Only adjustment I have is the final section says closed beta starts at 1.0.1, so I would propose the beta revisions milestones would be `1.0.1bX` or just `1.0.X`

@CBroz1 what would the next step here be? Re-name the versioning of specific issues with new milestones and add this updated versioning approach in the changelog or design doc? 
M

**Comment by CBroz1** [comment]
Sure - revised above to reflect your comment

Next step would be to edit existing labels and do a check over existing issues to make sure they're appropriately categorized.

**Comment by CBroz1** [comment]
@LockerM - I've revised the milestones and given them arbitrary due dates so they will be appropriately ordered when sorting by closest due date - [link](https://github.com/DeckofAdventures/TheGame/milestones?direction=asc&sort=due_date&state=open)

Does that work for you?

**Comment by CBroz1** [comment]
Implemented
