### ISSUE TITLE
Checks against own TC Flaw

### ISSUE THREAD

**Issue by D-D-2** [DeckofAdventures/TheGame#143]
Currently we have players maintain a TC and draw against it for certain checks. Unfortunately, this renders critical successes impossible to achieve. As a player, I would be disheartened upon this realization. 

Proposed Change 

Instead of drawing against their own TC, players draw against a TC drawn by the GM. This would include environment driven skill checks and saves. 

For example:
- "Your group moves through the brush in search of the signet. Make a detection check DR 1 against (draws from GM deck), a 2 of clubs.

**Comment by LockerM** [comment]
I agree that for environmental checks we absolutely want a GM to draw a TC and have the player draw against it. I had thought that was in the ruleset but I'm seeing it's missing from being explicit in two main sections of the PGF and the GM Guide. @D-D-2 can you double check the GM guide intro sections and see where some text would serve to clarify this for potential GMs? Seems like [this section of the GM guide](https://github.com/DeckofAdventures/TheGame/blob/main/docs/src/1_Mechanics/02_GMGuide.md#gm-preparation) should have a sentence or two clarifying exactly that.

The Player Guide Full also seems to be a bit confusing in the wording of a Player and a GM calling for a check and drawing. I think we should be explicit here as well in [this section of the PGF](https://github.com/DeckofAdventures/TheGame/blob/main/docs/src/1_Mechanics/01_PlayerGuide_Full.md#making-a-check).

**Comment by CBroz1** [comment]
The lazy way of navigating this complication would be to treat major successes as critical successes in this context

**Comment by D-D-2** [comment]
@LockerM Sure thing I'll look through both to see what seems missing or unclear and suggest edits. 
@CBroz1 thats certainly a quick solution, but not without its own problems. 3x the potential to have a critical success as opposed to a check against the GM or enemy, as well as adding a very specific rule detail that would make players and GMs repeatedly check the rule book to settle disputes. 

I would imagine myself as the GM hearing a player ask to climb a cliff and say "sure, make a brute check against my drawn TC." Eliminating draws against your own TC entirely and just having the checks be against a GM drawn TC or enemy's TC also can solve this problem and shorten the amount of rules in the GM guide/PGF

**Comment by LockerM** [comment]
The only time someone draws against their own TC is when making a Save. I'll make sure to make that explicit when writing Issue #111 into the PGF and GM Guide. Theoretically, there shouldn't be any need for a 'crit' save, and a Major Success is still a guaranteed save on a DR 0 which still gives the Player 3 chances to save there. 

All other checks are made against a TC drawn by the GM or another Player, whether in combat or in social/exploration encounters.

**Comment by LockerM** [comment]
Attempted resolution in #153.
