### ISSUE TITLE
Question: Is Lower Hand on all checks for Fatigue (1) too harsh?

### ISSUE THREAD

**Issue by LockerM** [DeckofAdventures/TheGame#152]
### Is Lower Hand on all checks for running out of cards between rests too harsh? 
*Note - does not need to be resolved before Beta testing current version of Fatigue*

We currently have it written where all checks are made with Lower Hand after running out of cards once, then Lower Hand (2) after running out again. Is this unnecessarily harsh? Are there specific types of Checks or Saves that should incur penalty after running out of cards once, maybe a movement speed penalty, and then all checks draw with Lower Hand on the 2nd level of Fatigue? 

Given that Quick Rests are only 30 minutes and should be taken fairly often, it's unlikely that except when in an extensive dungeon crawl or in a fast-paced life-or-death scenario that players won't be running out of cards too often, so Lower Hand on all checks feels like a solid penalty for that, though I wonder if having varying levels of Fatigue with different levels of complexity might make it more accessible for different types of Adventures where Fatigue can be a penalty the GM grants on some failed VIT checks for hiking a mountain range or diving underwater for too long, etc.

**Comment by D-D-2** [comment]
We could have a more severe penalty for running out of cards like 2 or 3 levels of exhaustion, but a less severe penalty for failing a Vit Save up a mountain like 1 level of exhaustion. 

This could be an exhaustion level system. Here's one proposal of what those levels could be: 
- Level 1: Lower hand (1) on saves. 
- Level 2: Movement Halved. 
- Level 3: Lower hand (1) on all checks. 
- Level 4: PP expenditure requirements doubled. 
- Level 5: Fate Cards cannot be used to gain upper hand 
- Level 6: Death

**Comment by CBroz1** [comment]
I like clarity of "all checks". New player then needing to recognize the difference between check and save could be difficult, but I don't feel strongly about it

**Comment by D-D-2** [comment]
Part of my rationale for the exhaustion levels being what they are was inspired by players who run out of cards getting lower hand 1 on both checks and saves as well as half their movement, so it's all wrapped into one.

**Comment by LockerM** [comment]
From playtesting yesterday, the Lower Hand (1) on all Saves as Fatigue level 1 worked really nicely and felt like a significant enough setback without being 'all' checks. One player needed to draw lower hand on a save to begin with and drew at lower hand (3) which felt successfully punishing for having run out of his deck of cards before resting.
