### ISSUE TITLE
Negative DRs and Theoretical Stat Max

### ISSUE THREAD

**Issue by LockerM** [DeckofAdventures/TheGame#175]
### Current State
Currently the system is designed with a DR 0 through DR 6 indicating the potential ranges of difficulty of a specific check. In a system that allows for stats up to a +6, even a DR 0 check becomes an auto-success at higher levels. 

### Questions to Resolve

1. Do we allow for Negative DRs? 

- These would signify tasks that anyone without a modifier couldn't even attempt. A DR -3 would mean if no one in the party had at least a +3 they would fail the check, and even at a +3 you're still attempting to draw a now DR 0 (still a very difficult check). 

2. If we allow for Negative DRs is our theoretical max skill/attribute cap still +6? 

- At a DR -4 that +6 is drawing a DR 2, certainly easier than a DR 0 but still a challenging check. Does the system then theoretically allow for a +12 at the absolute top of the scale (reserved for absolute insane BBEG level gods) but shift our player maximum to a +8 or a +10 at our theoretical max?

**Comment by CBroz1** [comment]
Addressed in #181
