### ISSUE TITLE
Should we revert to `Power Points`?

### ISSUE THREAD

**Issue by CBroz1** [DeckofAdventures/TheGame#60]
For 0.0.0a3, we changed to Fate Points, FP, for the better acronym. Does this overly link to Fate Cards, instead of associated with Powers?

**Comment by D-D-2** [comment]
With the consistent confusion I would have to agree. While I like the name "Fate Points" better from a flavor standpoint and potential inspiration for narrative play as a GM, I dislike players not remembering their Fate Cards are entirely separate from their Fate Points more.

**Comment by LockerM** [comment]
Addressed in PR #117.
