### ISSUE TITLE
Creature Connection - how many XP

### ISSUE THREAD

**Issue by CBroz1** [DeckofAdventures/TheGame#70]
Currently, the Powers list says Creature Connection costs 5 XP, and lists XP cost as 3. [link](https://github.com/DeckofAdventures/TheGame/blob/main/3_Automation/04_Powers.yml#L412-L415)

**Comment by CBroz1** [comment]
I bumped this to 5 XP [here](https://github.com/DeckofAdventures/TheGame/blob/main/3_Automation/04_Powers.yml#L416). Is that enough @LockerM ?

I don't think the companion needs a separate deck. I think that would make it very difficult to balance stamina

**Comment by LockerM** [comment]
Yea I agree @CBroz1, let's start with 5 XP to resolve the issue and lock it in and we can set this as one of the pieces we 'test' when character creation comes into play - does it feel worth giving up an Attribute boost or 2 Powers to acquire a Companion, especially when this then unlocks additional point investments into the Companion tree. 

For this next version, Companions will draw from the same Deck as the Dealer, and we can revisit down the road about the Companion eventually 'evolving' to become a Dealer themselves over time.

**Comment by LockerM** [comment]
I see in the current Powers list this is already at 5XP - I think we can close the issue if already resolved @CBroz1?

**Comment by CBroz1** [comment]
Only Q is whether or not to open an issue for 'Companion gets own deck' which I'd be against. 

Maybe we need one open issue (or some other doc) that's a graveyard. "Things we decided against, but you can try to resurrect if you'd like". With a top comment that gets edited

- Many minor actions
- Separate deck for companion
- etc

**Comment by CBroz1** [comment]
Closing, as this will be discussed on #13
