### ISSUE TITLE
Modify Poisoned Condition to affect Stamina instead of HP

### ISSUE THREAD

**Issue by LockerM** [DeckofAdventures/TheGame#73]
Right now the Poisoned Status Condition and the Burned Status Condition have a lot of mechanical overlap in terms of causing damage each turn until ended. 

What if Poisoned instead affects a character's Stamina (card count) by forcing a character to discard their top card on a failed Check to remove the Condition. This makes a creature that poisons a target a really useful mix for GMs as they work to get players to use and discard cards throughout session. 

Could be useful to add amplification to it over time if this works, meaning Poison can stack and force a character to discard 2 or even 3 cards after a failed Check (while still only requiring a single check to remove all instances of the poisoned condition for simplicity sake). 

What do you think @CBroz1 / @D-D-2 ?

**Comment by CBroz1** [comment]
@LockerM - Does it still make sense to say "poison bypasses AP" if it shouldn't impact HP? I think I saw beastiary proposal items that suggested poison damage type (impacting HP) in addition to or instead of poisoned status effect. We're currently vague on this.

**Comment by D-D-2** [comment]
There could be a separation between the _"Poisoned Status"_ and _"Poison Damage"_ . The Status effect could be the stamina drain, and the damage could be just like any other type of damage mechanic, where some creatures are vulnerable to it, resistant to it, or immune to it.

**Comment by CBroz1** [comment]
Currently, there's no mention of damage type in the player guide. We'd have to reevaluate #17

**Comment by CBroz1** [comment]
Closed by #88
