### ISSUE TITLE
'Help action' and Lend Aid

### ISSUE THREAD

**Issue by CBroz1** [DeckofAdventures/TheGame#77]
At present, there is no help action. This functionality is restricted to the Support role via Lend Aid, which, at present...

- Has no FP cost, making it a good go-to for a pacifist Support character
- Is a minor action, akin to sending a familiar around helping out in addition to a main action
- Has some overlap with the 'Help' discard mechanic that needs to be cleared up

After some discussion, we resolved to keep as is, but may revisit later

**Comment by CBroz1** [comment]
@LockerM - Please close if this is fixed by #105

**Comment by LockerM** [comment]
Closing this issue - to resolve with additional discussion found on #105.
