### ISSUE TITLE
'Dangling XP' on level up. Respec as default

### ISSUE THREAD

**Issue by CBroz1** [DeckofAdventures/TheGame#81]
Currently
- Respec'ing XP is dependent on GM permission. 
- On level up, 3 XP are granted, which is not enough for some higher level things, like Attrib +2 -> +3
- I could use 2XP on one power, and know I want a different 2XP power next, but not want to spent my 1XP, leaving it unused between levels 'dangling'
- 1 XP is a lot, if only 3 are awarded.

We could
- Always allow respec. Not sure of negatives in terms of changing character 'feel' between levels
- Only allow respec for dangling XP, but I don't think an objective decision is possible. 
- Add XP per level, making a dangling XP feel less important
- Do nothing - 'you just gotta wait'

**Comment by CBroz1** [comment]
See also #51

**Comment by CBroz1** [comment]
See also #92

**Comment by LockerM** [comment]
Dan likes the idea of players being able to respec on level-up, especially in long form campaigns.

Worth having a default House Rule #119 regarding respeccing to be explicit.

**Comment by LockerM** [comment]
Only allow -1 and -2 on Attributes at character creation as a limitation.
