### ISSUE TITLE
Add Discord bot

### ISSUE THREAD

**Issue by LockerM** [DeckofAdventures/TheGame#91]
## Current 

We are allowing for any and all ideas regarding DofA system mechanics to be considered in real-time as they come in from playtesters. As an Open Source platform, we encourage all ideas and contributions, but our current system stalls development when a new idea comes in rather than serving as a jumping off point for group discussion of the Contributors. 

## Potential Issue

Every playtest will result in numerous ideas and different people suggesting things of varying scope, new ideas for modifications of their own, as well as system analysis and feedback on the core mechanics themselves. If all ideas that come in must be analyzed and discussed immediately the Admins and core contributors will be stuck in 'react' mode rather than 'build' mode. 

## Proposal 

We attach milestone development to every playtester idea so it gets added onto the roadmap for consideration. We can encourage players to submit their own tickets (let's lower the barrier to entry and make it accessible by finding an email or Discord bot that will auto-create an Issue for people so they can submit them without needing to create a GitHub account as their first way of contributing), and then we can tag the issues as out of scope for upcoming development or leave them with a tag "For Consideration" and see what the community thinks about the ideas as they come in and over time. 

Then, we have design and development sprint kickoffs where the core Contributors assign the work going out of each area of the repo and we can then notify the people who submitted the issue that is being addressed in the next PR as well as those who commented on it that the idea they had talked about is going "Into Development" and can encourage them to contribute, and maybe even look for the person who would take the lead in drafting the PR and grow our core Contributors through the process.

## What this avoids

This will stop us from slowing down development after each individual playtest, and the contributors who are most excited about the possibilities to contribute will actively participate without a single contributor slowing down additional playtesting and development on the core system while talking about a feature or mechanic that might be better fitted for a later version or a "Deck of" spin-off system. Admins are guilty of this as well, where DofA development has been slowed by an idea more directly related to the "Deck of Erdania" system. These types of ideas are encouraged from the community, but should be considered independently of core DofA repo maintenance and development at the early stage of Closed Beta where we just need to refine the core system mechanics and playtest regularly. 

## What this allows

This will enable us to dramatically ramp up the speed of playtesting while still collecting player feedback and engaging them in the design and development process. The Discord and GitHub communities can then self-select the ideas most interesting, and we can leverage their interest in helping with that Issue to motivate them to Contribute to the PR and active development and maintenance of the GitHub. We can also provide a clear explanation of this process to players before and after they contribute an idea so they know how our development process works, and we can direct everyone who submits an issue to look at the "For Consideration" bucket of issues and add their own thoughts and ideas to them. This way we can funnel Contributor engagement to this group of Issues and let the Community be the ones who are actively driving what is being developed by their engagement with these Issues.

**Comment by CBroz1** [comment]
- [Discord issue bot](https://github.com/LeagueSandbox/IssueBot)
- @LockerM - What would resolve this issue? 
   - [ ] Adding the bot?
   - [ ] Adding a user-accessible channel with clear pinned instructions?

This may expose us to some spamming. We may be able to set issue default labels. 

FYI, there are other bots that manage issues - e.g. close after X days of inactivity

**Comment by CBroz1** [comment]
See also #116

**Comment by LockerM** [comment]
@CBroz1 thanks for finding that issue bot, I think having the Discord Bot and a user-accessible channel with clear instructions would help lower the barrier to entry for issue submission (or if it's easier via email as a v1) and resolve this issue. 

We've already added the 'For Consideration' and 'In Development' tags which was a big part of the initial issue submission, and I think your proposal for #116 should solve for the remaining items above.

**Comment by CBroz1** [comment]
[different bot repo](https://github.com/Booster1212/github-issue-bot)

**Comment by CBroz1** [comment]
- solved by [PR elsewhere](https://github.com/DeckofAdventures/TheBot/pull/1)
- issue closable on ... documentation? server(less) implementation?

**Comment by LockerM** [comment]
@CBroz1 I think having it built and running solves for the issue if we want to close/resolve. 

This then passes into that User Journey mapping we had discussed elsewhere of how players will find us and how they'll experience the game, where they'll drop feedback and how, and this solves really nicely the challenge of a general player not having a GitHub account and lowering the barrier to entry for them to submit 'official' feedback. 

Next steps on this would be for us to map out that user journey, add a channel in Discord with instructions of how to submit feedback using the GitHub bot, and having the GitHub bot locally hosted after a playtest or whenever one of us is online in Discord should work for our Closed Beta period.
