### ISSUE TITLE
Revise issue labels

### ISSUE THREAD

**Issue by CBroz1** [DeckofAdventures/TheGame#93]
- under consideration

**Comment by CBroz1** [comment]
I revised label names. Do you want to take a pass @LockerM ?

**Comment by CBroz1** [comment]
How do we divorce these and milestones from project management phases?

**Comment by LockerM** [comment]
Is there another good example of a repo or project that solicits feedback from the community and is in active development that we could draw inspiration from their issue labels?

**Comment by CBroz1** [comment]
There some variability in organization levels across these examples
- [numpy](https://github.com/numpy/numpy/labels?page=1&sort=name-asc)
- [mermaid](https://github.com/mermaid-js/mermaid/labels?page=2&sort=name-asc)
- [datajoint](https://github.com/datajoint/datajoint-python/labels)
- [deeplabcut](https://github.com/DeepLabCut/DeepLabCut/labels?page=2&sort=name-asc)

but also you could search any new thing you've heard about + "github issues" and you'll probably find a repo

**Comment by CBroz1** [comment]
Any further feedback @LockerM - I'm happy with status quo for now

**Comment by LockerM** [comment]
I'm happy with status quo for now as well @CBroz1 I think we can close/resolve for now and continue to add/update issue labels as specific use cases come up.
