### ISSUE TITLE
Missing: Cover Mechanic

### ISSUE THREAD

**Issue by LockerM** [DeckofAdventures/TheGame#95]
## Create a cover mechanic 

*From Community Feedback*

We can create and implement a cover mechanic for when a creature is behind partial or full cover.

### Proposed Mechanic

When a creature moves to a position that makes it more difficult to hit them, they will gain the effects of cover. 

*Partially Covered*: when a creature is still visible behind something but it is still reasonable to hit them. While under the effect of *partially covered* the creature gains +1 AR.

*Fully Covered*: when a creature is nearly impossible to see behind something and it is unlikely to land a hit on them. While under the effect of *Fully covered*, the creature gains +2 AR.

A creature can go from Fully to Partially Covered or from Fully Covered to Not Covered by using their Speed or making a Check. Some Powers may grant these effects as well.

**Comment by D-D-2** [comment]
Adding this mechanic will also add passive and or powers that can grant cover, negate cover, or get around cover.

**Comment by LockerM** [comment]
@D-D-2 - love it, I envision something like the below: 

**Dweller of the Dark** 
- When in partial or full darkness, receive the benefit of being *Partially Covered* (+1 AR)

**Unfazed Marksman** 
- When making a ranged attack against a Target in cover, add +1 to the draw.

**Comment by CBroz1** [comment]
Would I be partially covered from an enemy if positioned behind an ally? Behind another enemy?
