### ISSUE TITLE
Missing: Falling damage

### ISSUE THREAD

**Issue by LockerM** [DeckofAdventures/TheGame#96]
## Include explicit rules for Falling Damage

*Contributed from the Community*

Need a general rule for distance fallen translating into damage. Is insta-death a thing? Add in some more concrete rulings for GMs in their guide as well.

### Proposed Mechanic

Falling from a great height is dangerous. When you have fallen at least 10 feet, you take 1 damage. For every 10 additional feet, you take 1 additional damage. 

Falling from a height greater than 20 feet also leaves you Stunned for 1 minute. 

*No insta-death, but let's add something like the above Stunned condition to make higher falls feel even more dangerous*

**Comment by D-D-2** [comment]
I was thinking the same numbers for the height and amount of damage. Stunned after a fall is interesting. Was thinking about the option of taking away squares of movement depending on the height. 
"At 30 feet you lose two squares until you are healed."

**Comment by LockerM** [comment]
Oh @D-D-2 I like that a lot. By adding Stunned we would make it so you can move or take an action but not both, but I like the 'crippling fall' idea you propose above. I think since Stunned can be shaken off with a Check it's less meaningful for a big fall (if you're not in combat it doesn't make much of a difference), but the movement speed reduction is really compelling. See below for an updated proposal. 

### Crippling Fall
- Falling from a great height is dangerous. When you have fallen at least 10 feet, you take 1 damage. For every 10 additional feet, you take 1 additional damage and you lose 1 speed. This speed is recovered after a Rest or if you heal for at least 1 HP.

**Comment by D-D-2** [comment]
@LockerM Yes - I like the name crippling fall quite a bit too. Perhaps add an agility check between 20-40ft to see if the fall is crippling, but above 40ft, it's an automatic failure and deemed a crippling fall. @CBroz1 Thoughts? 

Only concern here is adding too many falling rules could add frustration to players.

**Comment by CBroz1** [comment]
> Falling from a great height is dangerous. At the end of a fall, a creature takes 1
damage and applies -1 speed for every 10 feet it fell and the creature is Knocked Down.
This speed is recovered after a Rest or if the creature is healed to their maximum HP.

With the current rule proposal, it doesn't have a distinct name, but allows a gradient impact without a check

**Comment by D-D-2** [comment]
The movement penalty starting at 10ft might be harsh. I also know my players always want the ability to make a check to avoid a penalty. So maybe the check is only to avoid the movement penalty but the damage is unavoidable?

**Comment by CBroz1** [comment]
Yeah, that makes sense. You can propose alternate wording [here](https://github.com/DeckofAdventures/TheGame/pull/127/files#r956602863) with the suggestion button. Maybe 
> And make a DR 3 VIT Check. If failed, they also take -1 speed for ...

**Comment by LockerM** [comment]
I think leaving as written for now works and we can test to see if players feel like falling requires a check. To me, a -1 speed penalty isn't too punishing and a player shouldn't need to make a check to avoid, but if we determined a worse penalty for a 40+ foot fall then I think that would warrant a check.
