### ISSUE TITLE
Missing: Lighting (dim, dark, etc.)

### ISSUE THREAD

**Issue by LockerM** [DeckofAdventures/TheGame#97]
## Need explicit ruling on partial and dark lighting 

When players enter a space, the amount of light should impact their Skill Checks, among other things relevant to the senses. 

**Full Darkness:** When making a Check in full darkness, draw with the Lower Hand. 

**Partial Darkness:** When making a Detection or Investigation Check in partial darkness, draw with the Lower Hand. 

### Adding Powers - Some examples below

These Powers could be useful for character creation as Passives relevant to their Race or character background.

**Darksight**: When making a Check in Partial or Full Darkness, you no longer draw with the Lower Hand. 

**Born in the Dark**: When in Full Darkness, you have Upper Hand when attacking.

**Comment by D-D-2** [comment]
Some of the sight abilities we come up with may relate to the different species of animal/insect folk too instead of passive abilities too.
