### ISSUE TITLE
Missing: Prone and Knocked Down Mechanics

### ISSUE THREAD

**Issue by LockerM** [DeckofAdventures/TheGame#98]
## Explicit mention of Prone and Knocked Down missing 

We currently have the **Knocked Down** Status Condition. Nothing explicit about voluntarily going prone. Below is a proposed mechanic to address.

## Proposed Mechanic 

When a character lays down, they are considered *Prone*. While Prone, melee attacks made from 1 space away are drawn at the Upper Hand, and ranged attacks made from more than 1 space away are drawn at the Lower Hand. 

You must use a Minor Action and expend half of your movement speed to stand up. This ruling works the same as the **Knocked Down** Status Condition.

**Comment by D-D-2** [comment]
I don't believe there are any melee attacks that can be made from more than 1 square away, but if at some point we do add a 2 square range melee attack, will we want to revisit the wording on this?

**Comment by CBroz1** [comment]
By the current wording - a long-range melee (e.g., spear from 2 spaces) would not gain the same benefit, and nor would a point-blank ranged attack gain the same detriment. I'm good with that
